#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Write the CP932 mapping table motionVmd decodes and encodes names with.

VMD names are Shift-JIS (CP932) fields, and they are decoded with a table the
project owns -- never an OS API, iconv, or the process locale
(docs/design/TEXT_ENCODING_POLICY.md §9, docs/design/MOTION_CONTRACT.md §4).
This script is that table's one author. It reads Python's `cp932` codec, which
implements Microsoft's CP932 (the code page MikuMikuDance writes with), and
writes `src/Cp932Table.inc`:

  * kSingleByte: every byte, as the code point it decodes to alone, or
    kLeadByte for the 60 bytes that start a two-byte character;
  * kDoubleByte: every (lead, trail) pair with trail 0x40-0xFC, as its code
    point, or 0 where CP932 maps nothing;
  * kEncode: every BMP code point CP932 can encode, sorted, with the bytes
    Microsoft's encoder chooses -- where several byte sequences decode to one
    code point (the NEC and IBM duplicates), the one it writes.

  generate_cp932_table.py            rewrite src/Cp932Table.inc
  generate_cp932_table.py --check    fail if the committed file differs
"""

from __future__ import annotations

import argparse
import pathlib
import sys

OUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "Cp932Table.inc"

LEAD_BYTES = list(range(0x81, 0xA0)) + list(range(0xE0, 0xFD))
TRAIL_FIRST, TRAIL_LAST = 0x40, 0xFC
LEAD_MARKER = 0xFFFF


def decode(data: bytes) -> int | None:
    try:
        text = data.decode("cp932")
    except UnicodeDecodeError:
        return None
    assert len(text) == 1 and ord(text) <= 0xFFFF, data.hex()
    return ord(text)


def rows(values: list[str], per_line: int) -> str:
    lines = []
    for start in range(0, len(values), per_line):
        lines.append("    " + ", ".join(values[start:start + per_line]) + ",")
    return "\n".join(lines)


def generate() -> str:
    single = []
    for byte in range(256):
        if byte in LEAD_BYTES:
            single.append(LEAD_MARKER)
            continue
        code_point = decode(bytes([byte]))
        assert code_point is not None, f"byte 0x{byte:02X} decodes to nothing"
        single.append(code_point)

    double = []
    for lead in LEAD_BYTES:
        for trail in range(TRAIL_FIRST, TRAIL_LAST + 1):
            code_point = decode(bytes([lead, trail]))
            assert code_point != 0
            double.append(code_point or 0)
    # A trail byte outside 0x40-0xFC never decodes: the table need not hold it.
    for lead in LEAD_BYTES:
        for trail in list(range(0, TRAIL_FIRST)) + list(range(TRAIL_LAST + 1, 256)):
            assert decode(bytes([lead, trail])) is None

    encode = []
    for code_point in range(0x10000):
        if 0xD800 <= code_point <= 0xDFFF:
            continue
        try:
            data = chr(code_point).encode("cp932")
        except UnicodeEncodeError:
            continue
        value = data[0] if len(data) == 1 else (data[0] << 8) | data[1]
        encode.append(f"{{0x{code_point:04X}, 0x{value:04X}}}")

    mapped = sum(1 for value in double if value)
    return f"""\
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by libs/motionVmd/tools/generate_cp932_table.py from Python's
// cp932 codec (Microsoft's CP932). Do not edit; rerun the script. The
// motionVmd_cp932_table test fails when this file and the script disagree.
//
// {mapped} two-byte and {256 - len(LEAD_BYTES)} one-byte characters decode;
// {len(encode)} code points encode.

inline constexpr std::uint16_t kLeadByte = 0x{LEAD_MARKER:04X};
inline constexpr std::uint8_t kTrailFirst = 0x{TRAIL_FIRST:02X};
inline constexpr std::uint8_t kTrailLast = 0x{TRAIL_LAST:02X};
inline constexpr std::size_t kTrailCount = {TRAIL_LAST - TRAIL_FIRST + 1};

// Byte -> code point, or kLeadByte.
inline constexpr std::array<std::uint16_t, 256> kSingleByte{{
{rows([f"0x{v:04X}" for v in single], 8)}
}};

// Lead bytes 0x81-0x9F then 0xE0-0xFC, each followed by its kTrailCount trail
// bytes 0x40-0xFC: (lead, trail) -> code point, or 0 when unmapped.
inline constexpr std::array<std::uint16_t, {len(double)}> kDoubleByte{{
{rows([f"0x{v:04X}" for v in double], 8)}
}};

struct EncodeEntry {{
    std::uint16_t codePoint;
    std::uint16_t bytes; ///< one byte when below 0x100, else lead << 8 | trail
}};

// Sorted by code point.
inline constexpr std::array<EncodeEntry, {len(encode)}> kEncode{{{{
{rows(encode, 4)}
}}}};
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed table differs")
    args = parser.parse_args()

    text = generate()
    if args.check:
        committed = OUT.read_bytes().decode("utf-8") if OUT.is_file() else None
        if committed != text:
            print(f"{OUT.name} differs from what {pathlib.Path(__file__).name} "
                  f"writes with Python {sys.version.split()[0]}; rerun it")
            return 1
        print(f"ok  {OUT.name} matches")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(text.encode("utf-8"))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
