// SPDX-License-Identifier: Apache-2.0
//
// CP932 through a table this project owns (src/Cp932Table.inc, generated by
// tools/generate_cp932_table.py) -- never an OS API, iconv, or the process
// locale (docs/design/TEXT_ENCODING_POLICY.md §9).
#pragma once

#include <cstddef>
#include <optional>
#include <span>
#include <string>
#include <string_view>

namespace motionVmd {

struct Cp932Decoded {
    /// Validated UTF-8; empty when `invalidAt` is set.
    std::string text;
    /// The last byte was a lead byte with no second byte, and was dropped.
    bool truncated = false;
    /// Where, within the bytes, a sequence CP932 does not map starts.
    std::optional<std::size_t> invalidAt;
};

/// Decodes `bytes` -- a field's content, without its padding -- in full. A
/// NUL is decoded like any other byte; stopping at one is the caller's rule.
Cp932Decoded DecodeCp932(std::span<const std::byte> bytes);

/// Encodes valid UTF-8 as CP932, choosing the bytes Microsoft's encoder
/// writes. Nothing when `utf8` is not valid UTF-8 or holds a code point CP932
/// cannot encode.
std::optional<std::string> EncodeCp932(std::string_view utf8);

/// `bytes` with every byte that starts no well-formed UTF-8 sequence replaced
/// by U+FFFD: for text a diagnostic quotes from outside the file -- a path, an
/// OS error -- never for a name, which is refused rather than repaired.
std::string ReplaceInvalidUtf8(std::string_view bytes);

} // namespace motionVmd
